name: Update Panel Image

on:
  workflow_dispatch:
env:
  PANEL_PROJECT_NAME: pterodactyl-panel # Dockerhub project
jobs:
  build_push_panel:
    name: Build and Push Panel Container
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Read Version
        id: read_version
        run: |
          echo "::set-output name=version::$(grep -Po "PANEL_VERSION=\K[^ ]+" ./manifest/version.txt)"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-panel-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-panel

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./manifest/images/panel
          file: ./manifest/images/panel/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.read_version.outputs.version }}
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PANEL_PROJECT_NAME }}:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.PANEL_PROJECT_NAME }}:${{ steps.read_version.outputs.version }}"
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
